# Generated by Django 5.2.3 on 2025-06-17 13:09

import django.db.models.deletion
import django.utils.timezone
import markdownx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_edicao', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('texto', markdownx.models.MarkdownxField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
