# Generated by Django 5.2.3 on 2025-06-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='chamada',
            field=models.TextField(blank=True),
        ),
    ]
